### PR TITLE
Add `--no-cgroups` to config

### PR DESCRIPTION
**Pull request by kpjensen**
To run `nvidia-container-cli` inside of unprivileged LXC.

### CODE REVIEW

**Comment by flx42** [comment]
`nvidia-container-runtime-hook` is for OCI runtimes, which LXC is not.

We have a custom hook for LXC, included in 3.0, did you test it?
https://github.com/lxc/lxc/blob/master/hooks/nvidia
Especially:
https://github.com/lxc/lxc/blob/master/hooks/nvidia#L217-L220

**Comment by kpjensen** [comment]
Thanks! Will take a look, closing this.

**Comment by flx42** [comment]
Cool, let me know if that works, it needs to be a `lxc.hook.mount`.

**Comment by kpjensen** [comment]
Ah I see, I am doing the terrible thing of running nested docker inside of unprivileged LXC. I have had this working with LXC by installing the driver on the host and bind-mounting the device nodes. This is attempting to use `nvidia-docker` inside of that. The two issues have been passing this `--no-cgroups` flag and that `nvidia-container-cli` always wants to set `CAP_SYS_MODULE` which I have dropped.

**Comment by 3XX0** [comment]
The capabilities issue is probably a bug if you have `load-kmods=false` in your `config.toml`, as for `no-cgroup` I suppose we could add an option to the config.

**Comment by kpjensen** [comment]
@flx42 Re-opening, would appreciate if it could be added.

**Comment by flx42** [comment]
Modified and pushed, thanks!

**Comment by kpjensen** [comment]
@flx42 thanks for this! `nvidia-docker` is working great inside unprivileged LXC.

**Pull request closed without merging**
