### PR TITLE
nvidia-container-runtime-hook: Get hook stage from stdin's 'status' value

### PR DESCRIPTION
**Pull request by wking**
Instead of using CRI-O-specific arguments, use the [state's REQUIRED `status` property][1] to ensure we're being called on a created container (and not a running container or a stopped container).

Also add [`fallthrough` statements][2] to the no-op switch cases, since that appeared to be the intention.

This is ground-work for dropping the stage environment variable from CRI-O (kubernetes-incubator/cri-o#1360), and should work for any CRI-O version.  The `args[0]` approach I'm replacing was [dropped][3] from CRI-O in kubernetes-incubator/cri-o#1244.

[1]: https://github.com/opencontainers/runtime-spec/blame/v1.0.1/runtime.md#L16
[2]: https://golang.org/ref/spec#Fallthrough_statements
[3]: https://github.com/kubernetes-incubator/cri-o/pull/1244/files#diff-dba9598e19f7903533dc9add98d410d2L431

### CODE REVIEW

**Comment by flx42** [comment]
> Instead of using CRI-O-specific arguments

It's not, really. As long as it's setup properly, for instance it works fine with docker since we inject the hook + `prestart`.

Initially the syntax was `nvidia-container-runtime-hook -prestart`. Then I saw CRI-O and realized it made sense to drop the `-`, like a command/action. But I also complained that passing the stage as the first argument was indeed undocumented, so I asked for the possibility to pass custom arguments to hooks and suggested the environment variable as an alternative. If `prestart` stops being injected by CRI-O, you should add it to your hook configuration file like I initially wanted to do.

**Comment by flx42** [comment]
In addition, `runc` doesn't seem to set this field.

**Comment by wking** [comment]
Some notes on runc support [here][1].

[1]: https://github.com/projectatomic/oci-umount/pull/35#issuecomment-368236335

**Comment by flx42** [comment]
Uh, the right struct from the OCI spec was pulled in, but it still doesn't seem to be set inside of runc before the prestart hooks, right?
https://github.com/opencontainers/runc/blob/master/libcontainer/process_linux.go#L345-L351

**Comment by wking** [comment]
> ... but it still doesn't seem to be set...

Heh, nice.  I'll file runc and runtime-tools validation PRs later.  Probably table this PR for now.

**Pull request closed without merging**
